Repository breez/c-breez, pull requests merged in 2023-10, with the labels that each got.

#639 allow export of static backup
  lib/bloc/account/account_bloc.dart
  lib/bloc/account/credentials_manager.dart
  lib/routes/dev/developers_view.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, QA-testing

#696 Make route logging logs just the route name to avoid logging sensitive data shared through route arguments
  lib/user_app.dart
Labels: high priority

#684 use mempoolInstance across the app.
  lib/bloc/network/network_settings_bloc.dart
  lib/routes/home/widgets/payments_list/dialog/closed_channel_payment_details.dart
  lib/routes/subswap/swap/widgets/inprogress_swap.dart
  lib/routes/withdraw/reverse_swap/in_progress/reverse_swap_in_progress.dart
  lib/utils/blockchain_explorer_utils.dart
  test/bloc/network/network_settings_bloc_test.dart
Labels: QA-testing
